
class DataIngestionArtifacts : ...
class DataValidationArtifacts : ...
class DataTransformationArtifacts : ...
class DataTrainerArtifacts : ...
class DataEvaluationArtifacts : ...
class DataPusherArtifacts : ...